### ISSUE TITLE
Release into ROS Build Farm

### ISSUE THREAD

**Issue by rctoris** [ccny-ros-pkg/phidgets_drivers#16] opened 2015-01-12 16:52 UTC
We were wondering if this could be released into the ROS build farm to use as a ROS dependency for some of our released code. We have verified that this package also works in Indigo.

**Comment by mintar** [comment] 2015-01-13 09:05
+1

**Comment by muhrix** [comment] 2015-01-13 12:52
I could do that, but I'd need to create a release repository outside ccny-ros-pkg (I'm restricted to write permission to this repo).
If there are no objections, I can set up the release repo in my account and have this repo as the upstream.

Any thoughts?

**Comment by mintar** [comment] 2015-01-13 12:53
No objection here. That's what I did for ccny-ros-pkg/imu_tools.

**Comment by muhrix** [comment] 2015-01-15 18:09
All set. `phidgets_drivers` should be released for Hydro and Indigo soon.
I'll close this issue once they're available.

**Comment by dirk-thomas** [comment] 2015-02-03 19:13
The currently released package `phidgets_api` tries to install files in the global system folder when being compiled/packages into a Debian package.

The build process does not have root access on the build farm. You need to modify the build process to succeed on the build farm: http://jenkins.ros.org/view/IbinT64/job/ros-indigo-phidgets-api_binarydeb_trusty_amd64/20/console (see `Permission denied`)

**Comment by muhrix** [comment] 2015-02-03 19:29
Hi @dirk-thomas,

I am ware of that, and I do apologise for the waste of resources whilst attempting to build the package.

The issue is that I am using `CATKIN_DEVEL_PREFIX` env variable, which appears not to be set in the build farm setup. When I run on my computer, it goes under `catkin_ws/install/lib`, rather than `/lib`.

Regardless, the package is currently breaking REP136, and I found out there is a (also non REP136-compliant) `libphidgets` package already released, but with slightly different version of the phidgets library.

I was hoping someone would be able to test a workaround I committed to the `libphidgets` branch, because for the past few weeks I did not have time to work on this issue myself.

I should be able to fix this by the end of next week though, when I'll have access to a phidgets IMU again.

**Comment by dirk-thomas** [comment] 2015-02-03 19:43
No worries about the resources. I just noticed it on our new build farm and though I comment on it briefly.

`CATKIN_DEVEL_PREFIX` is always set by `catkin` - also on the build farm. The problem is that you are trying to use the variable (https://github.com/ccny-ros-pkg/phidgets_drivers/blob/bc516d10d0a3cd5ed8b8072f425f84def50405f7/phidgets_api/CMakeLists.txt#L36) before finding `catkin` (https://github.com/ccny-ros-pkg/phidgets_drivers/blob/bc516d10d0a3cd5ed8b8072f425f84def50405f7/phidgets_api/CMakeLists.txt#L47). You need to reorder the CMake file.

**Comment by mintar** [comment] 2015-03-25 17:47
This is solved now for indigo with version 0.2.2. Thanks @muhrix !

I have just tried 0.2.2 on hydro, and it also works. Could you release 0.2.2 into hydro as well? It should be as easy as:

    git checkout hydro
    git merge --ff-only origin/indigo
    git push

... and then follow the usual `bloom release` steps. No need to run `catkin_generate_changelog` or `catkin_prepare_release`, since these were already done when releasing into indigo.

**Comment by muhrix** [comment] 2015-03-25 17:52
@mintar  I've already done it, not sure how long the process takes in the build farm, but it should be available at some point (soon-ish, I guess).

I am considering this issue as resolved then.
Thanks for testing on hydro!

**Closed by muhrix** 2015-03-25 17:52 UTC
